### ISSUE TITLE
debug issue?

### ISSUE THREAD

**Issue by oliverzy** [vuejs/vue-loader-example#23]
When I debug the example in Chrome & Safari, I found some strange behavior.

For example, suppose I set a breakpoint at line 16, file `counter.vue`.
And when the breakpoint is hit, if I put the cursor on 'this', it displays 'Window' object, not the 'Vue' instance.

**Comment by yyx990803** [comment]
This is because although Chrome dev tools is showing you the ES6 source code, the actual executed code is still the compiled ES5 code. Babel transforms arrow functions by saving the outer `this` as `_this`, and in the compiled function `this` still points to window.

**Comment by oliverzy** [comment]
Thanks, it seems a chrome source map limitation here.
But because the arrow function is supported since Chrome 45, it's okay to remove arrow function transpile plugin from babel during the development phase.
