### ISSUE TITLE
能否用vue-loader 实现webpack的demo

### ISSUE THREAD

**Issue by henjue** [vuejs/vue-loader-example#24]
能否用vue-loader实现https://github.com/vuejs/vue-webpack-example  的效果
最近学习vue，打算使用vue-loader的方式来实现vue-webpack-example 的效果（define the main pages as async components.）
但是发现1.0.0之后的vue不能现实component的data

**Comment by yyx990803** [comment]
什么叫不能现实 component 的 data

**Comment by henjue** [comment]
```vue
<template>
    <div class="view" transition>
      <head msg="{{ msg }}"></head>
      <pane side="left" name="{{ leftName }}"></pane><!--浏览器打开之后这里显示的是"{{ leftName }}"字符串而不是变量leftName的值“Bruce Lee”-->
      <pane side="right" name="{{ rightName }}"></pane>
    </div>
</template>
<script>
import head from '../components/header.vue'
import pane from '../components/pane.vue'
export default {
  replace: true,
  data() {
    return {
      msg: 'This is page A.',
      leftName: 'Bruce Lee',
      rightName: 'Chuck Norris'
    }
  },
  components:{head,pane}
  }
</script>
```

**Comment by henjue** [comment]
如果换成别的标签，比如<p>、<h1>之类的只要不是组件(pane或head)都可以正常显示。

**Comment by suhaotian** [comment]
如果用 vue-loader 写异步组件该怎么弄，希望 example 有个例子

**Comment by yyx990803** [comment]
1.0 props 的语法不一样，请看文档。

**Comment by henjue** [comment]
@yyx990803 就是看了文档的。除了命名大小写转成xxx-xxx的格式也没其他的。已经尝试过各种猜测，文档反复看了不知道多少变量。然后不行

**Comment by yyx990803** [comment]
用 `:name="leftName"`

**Comment by henjue** [comment]
@yyx990803 那pane 里的props:['name']又不能获取了，已经试过。

**Comment by yyx990803** [comment]
那你的 pane 实现肯定有问题...

**Comment by henjue** [comment]
@yyx990803 感谢。我理解错文档了。认为:name="leftName" 传递给组件的是字符串"leftName"而不是变量leftName。非常感谢
