### ISSUE TITLE
.vue vs. .html file extension

### ISSUE THREAD

**Issue by thisconnect** [vuejs/vue-loader-example#25]
Hi I absolutely love the combined trinity (HTML/CSS/JavaScript) in the components and the ability to use less/stylus/whatever i.e. https://github.com/vuejs/vue-loader-example/blob/master/src/app.vue

Since a `.vue` file is almost valid HTML (+ doctype and title) would it be allowed or not recommended to use the `.html` file ending, or something custom like `.vue.html`?

Using `.html` already seems possible, with changing the webpack config. Is this forward compatible or are there plans to only support `.vue` in the future?  

The team where I would like to introduce vuejs would probably love if we do not have a new file extension. If `.html` is OK, I would open a feature request on the vue syntax highlighter to allow other file extensions that `.vue`.

Thanks

**Comment by yyx990803** [comment]
Yeah it should be totally fine to use whatever extension you want.

**Comment by thisconnect** [comment]
Thanks!
