### ISSUE TITLE
css for component doesn't compile right

### ISSUE THREAD

**Issue by greennyreborn** [vuejs/vue-loader-example#3]
In file 'a.vue',
```
<style>
comp-a h2 {
  color: #f00;
}
</style>
```

In the compiled html,  css remain the same:
```
<style type="text/css">comp-a h2 {
  color: #f00;
}</style>
```

apparently these is no tag as 'comp-a', so the color makes no difference

**Comment by posva** [comment]
That's normal: the `<comp-a>` is replaced by the content of the component itself. Therefore it doesn't exist anymore in the DOM.

**Comment by yyx990803** [comment]
Closing as this is no longer relevant
