### ISSUE TITLE
npm run dev can't access website

### ISSUE THREAD

**Issue by cuitianze** [vuejs/vue-loader-example#33]
Windows Platform:   
![run-server](https://cloud.githubusercontent.com/assets/5918515/11526329/b324e79c-9914-11e5-9fa2-0956b7ce6c9f.png)

l start the server correctly, however l can't open the website.

![error](https://cloud.githubusercontent.com/assets/5918515/11526372/f5217a5c-9914-11e5-85f6-97bc711f5ae5.png)

**Comment by yyx990803** [comment]
Node 版本？确保依赖都正确安装

**Comment by cuitianze** [comment]
Maybe packages installed failed.
```
rm -rf node_modules
```
try `npm install` again, then it works.
