### ISSUE TITLE
Hot-reload does not work

### ISSUE THREAD

**Issue by jingsam** [vuejs/vue-loader-example#35]
After running `npm run dev`, the hot-reload works great except I alter [Hello from Component A!](https://github.com/vuejs/vue-loader-example/blob/master/src/components/a.vue#L20). I need to refresh manually to take effects.

node v5.1.0
npm 3.3.12
Windows 10

**Comment by yyx990803** [comment]
Because you modified the **initial data** for that component. The reload persists the current state for the component.
