### ISSUE TITLE
chrome://browser/ added to background-image url?

### ISSUE THREAD

**Issue by avitex** [vuejs/vue-loader-example#43]
I've tried a few times to get this working, but in both Chrome *and* Firefox, a link to a static image referenced from CSS does not load.
Interestingly enough, I found in the browser inspectors for both Chrome and Firefox, the image is shown as 'Couldn't be loaded', and when the URL is copied, it's prefixed with "chrome://browser/".

**Example background image URL shown in the inspector**
![Inspector screenshot](https://i.gyazo.com/985bafd77028db41735260e4a06047cd.png)

**Right click, and copy URL produces this**
`chrome://browser/static/images/bg.jpg`

**Manually entering in the correct URL, as what would be expected, works**
![Address bar screenshot](https://i.gyazo.com/fc7e56b0e0adb655ec299cbf34079888.png)

Thanks in advance :smiley: 

**EDIT**
The URL to be more precise, when copied from Chrome is:
`chrome-devtools://devtools/bundled/"/static/images/bg.jpg"`
and when copied from Firefox is:
`chrome://browser/static/images/bg.jpg`

**Comment by almini** [comment]
I had the same issue. It looks like it's related to source map support.
If you remove ```config.devtool = 'eval-source-map'``` it should work.
The css is then inlined in a style-tag and not included using the link-tag referencing a blob.

**Comment by yyx990803** [comment]
Unfortunately this is a bug/limitation of `style-loader`. I may have to fork it to get around this...

**Comment by yyx990803** [comment]
This should now be fixed in `vue-loader@8.0.0`. Note you will need to install `vue-style-loader` as a peer dependency now instead of `style-loader`.
