### ISSUE TITLE
Maybe should use `Vue.extend()` to generator components from `.vue` file?

### ISSUE THREAD

**Issue by TooBug** [vuejs/vue-loader-example#5]
<https://github.com/vuejs/vue-loader-example/blob/master/src/main.js#L3>

This line in example code doesn't work in my code (with vue-router).

```
var component = new Vue(appOptions);
```

In my opinion, in this way ,the `component` should be a `view-model`, but not component.

The correct version is:

```
var component = Vue.extend(appOptions);
```

I'm a starter user of vue.js, so not very clear of the difference, just open this issue to confirm.

**Comment by yyx990803** [comment]
`new Vue()` creates an instance. `Vue.extend` returns a constructor.

You can do

``` js
var Component = Vue.extend(appOptions)
var component = new Component()
```

The result is the same.

**Comment by TooBug** [comment]
Very clear, Thanks!
