### ISSUE TITLE
ERROR in Cannot find module 'stylus'

### ISSUE THREAD

**Issue by PrimozRome** [vuejs/vue-loader-example#55]
After `npm update` I get this error:

ERROR in Cannot find module 'stylus'
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue 4:14-240 13:2-17:4 14:20-246

This was working fine before npm update. I have removed stylus and stylus loader and installed them again but does not help... Any idea?

In my app.vue I have some stylus styles

```
<style lang="stylus">
...
</style>
```

**Comment by yyx990803** [comment]
stylus-loader 2.0 now needs stylus as a peer dependency.

**Comment by PrimozRome** [comment]
Ok trying to understand what that means... Meanwhile I have fixed this with installing stylus as a local package not global (-g). Then it worked.

**Comment by app-sparkler** [comment]
`npm install -D stylus-loader stylus`
