### ISSUE TITLE
access to "data" from methods

### ISSUE THREAD

**Issue by hekigan** [vuejs/vue-loader-example#6]
Hi, 

I really love vue.js and feel that it's fairly simple and nice to use.
But since I tried to use it with es6, I run into the following issue:

```
export default {
    el: '#app',
    template: require('./template.html'),
    data() {
        return {
            name: 'Bob'
        };
    },
    methods: {
        hello: () =>  {
            return this.name;
        };
    },
}
```

"this" is undefined so what would be the recommended way to access data from methods?

**Comment by hekigan** [comment]
My bad, the code below was enough...
```
hello: function()  {
  return this.name;
};
```

Basically, the fat arrow take the current 'this' and since it's only an object, it's not defined yet.

**Comment by sjoerdvisscher** [comment]
Or:

```
hello()  {
  return this.name;
};
```

**Comment by wagnerandrade** [comment]
@sjoerdvisscher :+1:

**Comment by vplugues** [comment]
@hekigan Do you know why is this? 

I was having this issue today. I am wondering why es6 function shorthand does this. Is it the shorthand method? or is it Vue?
